# This is a basic workflow to help you get started with Actions

name: Build project and push to gh-pages

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [Not-a-branch]
    # branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: fetch branches
        run: git fetch

      - name: build all the dependencies
        run: yarn

      - name: build the distribution and put it into a docs folder
        run: yarn gh-pages-build

      # NOT USED
      # For building: stash everything if there are things remaining to be stashed
      # - name: stash everything else
      #   run: git stash

      # NOT USED
      # For testing: add an artifacts folder with a file
      # - name: adding test artifacts folder with file
      #   run: yarn gh-pages-test-build-2

      # NOT USED
      # For testing: add a docs folder with a file
      # - name: build the project and put it into a docs folder
      #   run: yarn gh-pages-test-build

      - name: checkout gh-pages
        run: git checkout gh-pages

      # NOT USED
      # For testing: add all changes has to go here for testing.
      # - name: add all changes from the build
      #   run: git add -A

      # NOT USED
      # For the build, but should be removed for testing (since artifacts will not exist)
      # - name: remove the artifacts
      #   run: git reset -- artifacts

      - name: run ident email
        run: git config --global user.email "janke.aaron@gmail.com"

      - name: run ident name
        run: git config --global user.name "Aaron Janke"

      - name: check git status
        run: git status

      - name: add all
        run: git add docs

      - name: commit with build message
        run: git commit -m 'github action updating the build'

      - name: push the changes to gh-pages
        run: git push
